Q2. Row Echelon Form:

In [1]:
import numpy as np

# Set random seed
np.random.seed(31)

# Create a random 5x5 matrix A with integers between 0 and 9
A = np.random.randint(0, 10, size=(5, 5))

print("Original Matrix A:")
print(A)

# Perform elementary row operations to reduce A to row echelon form
for i in range(min(A.shape)):
    # Find the pivot
    pivot_index = np.argmax(A[i:, i]) + i
    # Swap rows if necessary
    if pivot_index != i:
        A[[i, pivot_index]] = A[[pivot_index, i]]
    # Make the pivot entry 1
    A[i] = A[i] / A[i, i]
    # Eliminate entries below the pivot
    for j in range(i + 1, A.shape[0]):
        A[j] = A[j] - A[j, i] * A[i]

print("\nRow Echelon Form of Matrix A:")
print(A)

Original Matrix A:
[[2 7 0 2 7]
 [6 6 2 2 9]
 [1 7 1 1 4]
 [6 3 3 2 8]
 [7 8 1 4 8]]

Row Echelon Form of Matrix A:
[[1 1 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 1]
 [0 0 0 0 1]]
